package ast

// every detail

// structural detail 

// implicit grouping parenthesis

// types used

// 3 main classes 

// corresponding go spec production names

// individual parts


// marking beginning of construct

// additionnal position info

	// found between parts of the construct

		// larger, parenthesized subpart

// properly position comments



// all nodes

// 


// assigned to Expr

// assigned to Stmt

// assigned to Decl



// single Comment

// present insource

// computed end position

// true source end position


// no other tokens | no empty lines between


// white space

// text

	// removed comments markes | first space | leading-trailing empty lines
	// removed directives
	// trailing space trimmed
	// new-line terminated

// comment directive





// unamed parameter
// embedded struct fields

// enclosed list of fields

// concrete expression node

	// bad expression

	// denoted object

	// parameter list only

	// basic literal

	// anonymous function

	// compositie literal -> missing in the elts list

	// parenthezised expr

	// followed by selector

// indicated channel direction

// type-specific expression node

	//ArrayType

	// StructType

	// ...

// generated by code other than go parser


// concrete statement nodes

	// no correcr statement

	// DeclStmt

	// immediately following ; omitted

	// braced statement



// Declarations

// single non-parenthesized 

	// generic decl

	// func decl


// file

	// all comments

	// comments intersepted

	// relevant comments

	// associated doc

	// file only

	// top-level


// package

	// accross files

	// 




